PANDAS

In [ ]:
Listas : Serie de elementos de diferentes tipos mutables 
tupla : Serie de elemetos de diferentes tipos inmutables 
Diccionario : Serie de elemento con dos componentes (clave , valor)
Array : Serie de elementos de un mismo unico tipo de dato

In [ ]:
# Series (array) vs Numpy
# Dataframes (filas y columnas) #Indices y nombres ()
# Paneles (+ 2 dimensiones)

In [2]:
#Estas son las 3 formas para importar una librerias 

import pandas as pd 

import pandas 

from pandas import (

    read_csv,
    read_xml,
    read_excel
)

In [4]:
#Generar un dataframe a partir de una lista.
data = [['juan',32],['Arnolfo',45],['Patricia',34]]

#Asignar nombres y crear el dataframe
df = pd.DataFrame(data,columns=['nombre','edad'])

In [5]:
df

     nombre  edad
0      juan    32
1   Arnolfo    45
2  Patricia    34

In [6]:
#Crear un dataframe desde un diccionario 
data = {
'Nombre' : ['Juan', 'Luis','Julian'],
'Edad' : [25,24,34]
}

#Generamos el dataframe 
df = pd.DataFrame(data)

In [7]:
df

   Nombre  Edad
0    Juan    25
1    Luis    24
2  Julian    34

In [8]:
#leer un archivo csv local 
df = pd.read_csv('./utils/data/data.csv')
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [9]:
#leemos un archivo que no tiene cabecera 
df = pd.read_csv('./utils/data/data_without_header',
                 header=None,
                 names= ['Nombre','edad','ciudad']
                 )
df

  Nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [ ]:
#Leer un archivo sin extension con un diferente separador 

df = pd.read_csv('./utils/data/data',               
                 sep= '|'
                 )
        
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [10]:
#Leer archivo json
df = pd.read_json('./utils/data/data.json')
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

METODOS DATAFRAME

In [ ]:
#Describe te da las estadisticas descriptivas 
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [24]:
#listar top n elementos
df.head(1)

  nombre  edad  ciudad
0   Juan    25  Madrid

In [25]:
#listar bottom n elementos 
df.tail(2)

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [11]:
#extraer columnas 

df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='object')

In [12]:
#Extraer los indices 
df.index

RangeIndex(start=0, stop=3, step=1)

In [13]:
#Agrupa por cada una de las columnas y contabiliza los valores no nulos
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

Acceder valores con dataframe

In [14]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [16]:
#Seleeciona una columna 
df['ciudad']
#Selecciona mas de una columna
df[['ciudad','edad']]

      ciudad  edad
0     Madrid    25
1  Barcelona    30
2    Sevilla    35

In [20]:
#seleccionar una fila por su indice
print(df.loc[2])

print("#####\n")

print(df.loc[[0,2]])

print("#####\n")
#Seleccionar columnas que cumplan cierta condicion 
print(df[df['edad']>=30])

nombre      Pedro
edad           35
ciudad    Sevilla
Name: 2, dtype: object
#####

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla
#####

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

Agrupaciones

In [24]:
#Crear un dicionario con grupos y valores
data = {
    'Grupo': ['A', 'B', 'A', 'A', 'B'],
    'Valor': [12, 34, 23, 45, 33]
}

#creamos el dataframe
df = pd.DataFrame(data)

#promedio de valor por grupo 
promedio_por_grupo = df.groupby('Grupo').mean()
print(promedio_por_grupo)

print('#####  \n')
#Suma por valores
suma_por_grupo = df.groupby('Grupo').sum()
print(suma_por_grupo)

           Valor
Grupo
A      26.666667
B      33.500000
#####

       Valor
Grupo
A         80
B         67

In [26]:
#leemos la data sin extensiones 
df = pd.read_csv('./utils/data/data', sep = '|')
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [31]:
#NaN Not a Number (datos numericos faltantes)
#None Ausencia de valor 
#Null "No existe en python" 


#eliminar las filas que contienen vlores desconocidos (Nan)
df_sin_na = df.dropna()
print(df_sin_na)

print("\n")


#Reemplazar NaN con otros valores 
df_completo = df.fillna(value=0)
print(df_completo)

  nombre  edad     ciudad
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


  nombre  edad     ciudad
0   Juan   0.0     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [33]:
df_sin_na = df.dropna(subset=['ciudad'])
print(df_sin_na)

print("\n")

df_completo_final = df['edad'].fillna(value=0)
print(df_completo_final)

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


0     0.0
1    30.0
2    35.0
Name: edad, dtype: float64

FUNCIONES EN UN DATA FRAME

In [34]:
#Dataframe ejemplo
data = {
    'A': [1,2,3,4],
    'B': [6,7,8,9]
}

df = pd.DataFrame(data)

In [36]:
#Calcular un nuevo campo que duplique el grupo A
df['A_doble'] = df['A'].apply(lambda x: x*2) 
df

   A  B  A_doble
0  1  6        2
1  2  7        4
2  3  8        6
3  4  9        8

In [39]:
def multiplo2(x):
    return x*2

df['A_doble_2'] = df['A'].apply(multiplo2)
df

   A  B  A_doble  A_doble_2
0  1  6        2          2
1  2  7        4          4
2  3  8        6          6
3  4  9        8          8